### ISSUE TITLE
New update breaks YTKillerPlus entirely...

### ISSUE THREAD

**Issue by eyeslow** [iKarwan/YTKillerPlus#22]
With the newest update **18.19.1 - 2.2.12** there is no tab bar icon for YTKillerPlus and if I try to tap on it to configure it's settings, YouTube crashes. Also the buttons in the video player overlay are not showing up at all, something went wrong with the latest release...

**Comment by iKarwan** [comment]
sorry for that 

no i just forget to include the bundle 
it has been immediately fixed u can try to re download / reinstall it
