### ISSUE TITLE
Activation code page not working

### ISSUE THREAD

**Issue by BaffleBlend** [iKarwan/YTKillerPlus#29]
I've purchased YTK+, and it tried to open the page to generate the activation code. The problem is, I got a warning that the page isn't supported on desktop and to please open on mobile.
I AM on mobile, and I've tried multiple mobile browsers trying to solve this problem. So I'm essentially locked out of activation.

**Comment by thomasthebear** [comment]
Did You Use Safari? If So, Make sure you've disabled any extensions to verify that isn't the issue.

**Comment by iKarwan** [comment]
> I've purchased YTK+, and it tried to open the page to generate the activation code. The problem is, I got a warning that the page isn't supported on desktop and to please open on mobile. I AM on mobile, and I've tried multiple mobile browsers trying to solve this problem. So I'm essentially locked out of activation.

hey pls can u contact throgh the support on X/twitter @ikg_support  or email ikghd3@gmail
the support will handle it
