### ISSUE TITLE
PiP button broken

### ISSUE THREAD

**Issue by l4kr** [iKarwan/YTKillerPlus#55]
### Describe the bug

```yaml
When I press the PiP button in the video it just shows the menu with external players.

Also, it would be nice to have PiP activate automatically on exit like in uYou instead of having to press the button.

Version 3.2.47
```

### Steps to reproduce

```yaml
1. Press PiP button
```

### Post Requisites

- [X] I have checked that a similar issue has not been reported before.
- [X] Verified the relevance of the project and the version you are using.
- [X] Provided a detailed description of the problem and have filled in all required fields.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.
- [X] By submitting this issue, **I confirm that I have filled in all the necessary fields and complied with the guidelines. Failure to comply may result in the issue being closed without discussion, and repeated violations may lead to restrict account from further participation.**

**Comment by iKarwan** [comment]
on newer version has stoped there's no workaround for it for now sure it will be fixed once a proper one found
