### ISSUE TITLE
This need an update and fix download

### ISSUE THREAD

**Issue by JackPlaysGames0510** [iKarwan/YTKillerPlus#8]
Some features don’t work can you update them also download doesn’t work

iPhone 12 Pro Max

16.3

**Comment by JackPlaysGames0510** [comment]
Also can you add a feature that keeps the volume bar red

**Comment by iKarwan** [comment]
can u specified the features were not working ?

and download is fine all with all versions including 16.4 were tested!

**Comment by JackPlaysGames0510** [comment]
Download doesn’t work properly on a paid certificate if I download a video that is 10 minutes or more then the it doesn’t download properly not play if I tap on the video

**Comment by JackPlaysGames0510** [comment]
And i am on 16.3

**Comment by JackPlaysGames0510** [comment]
And if if I tap on the download button the name on top says null sometime

**Comment by JackPlaysGames0510** [comment]
And if I minimise it the number just freeze

**Comment by JackPlaysGames0510** [comment]
Ok so I found out that it does work but I have to kill the app and open it for it to work
